### PR TITLE
Add CPLEX

### PR DESCRIPTION
**Pull request by joaquimg**
For this one to work we need to add @odow to the repo, so that he can add the env variables in Travis.
We might still need to move to JuMP-dev, not sure...

### CODE REVIEW

**Comment by blegat** [comment]
@odow has write access to the repo. I didn't move it to jump-dev to avoid adding this big CI load but we can move if needed

**Comment by joaquimg** [comment]
Makes sense. This is very heavy.
It might even justify an organization holding only this so that we can setup weekly/daily tests...

**Comment by odow** [comment]
I have write access but not admin access to add secrets. Let's just move this to jump-dev? CI is no longer an issue

**Comment by blegat** [comment]
Done :)

**Comment by odow** [comment]
Closing in favor of #14

**Pull request closed without merging**
